---
title: "Multivariate (PSY 5246C) - Fall 2022"
---

Syllabus: [HTML](files/Multivariate syllabus Fall 2022.html) [PDF](files/Multivariate-syllabus-Fall-2022.pdf)

Update syllabus with schedule update 1: [HTML](files/Multivariate syllabus Fall 2022 update1.html) [PDF](files/Multivariate-syllabus-Fall-2022-update1.pdf)

[Lecture videos on Youtube](https://www.youtube.com/playlist?list=PLKrGRYggZL-Ep68y7UMzHwSEHoXlszMyI)

| Week | Topic                           | HTML slides | PDF handout |
|------|---------------------------------|-------------|-------------|
| 1    | Matrix algebra                  | [Mult22-1.html](files/Mult22-1.html) | [Mult22-1.pdf](files/Mult22-1.pdf) |
| 2    | Linear regression               | [Mult22-2.html](files/Mult22-2.html) | [Mult22-2.pdf](files/Mult22-2.pdf) |
| 3    | Linear regression               | [Mult22-3.html](files/Mult22-3.html) | [Mult22-3.pdf](files/Mult22-3.pdf) |
| 4    | Logistic regression             | [Mult22-4.html](files/Mult22-4.html) | [Mult22-4.pdf](files/Mult22-4.pdf) |
| 5    | Poisson regression              | [Mult22-5.html](files/Mult22-5.html) | [Mult22-5.pdf](files/Mult22-5.pdf) |
| 6    | Matrix algebra                  | [Mult22-6.html](files/Mult22-6.html) | [Mult22-6.pdf](files/Mult22-6.pdf) |
| 7    | Principal component analysis    |             |             |
| 8    | Factor analysis                 |             |             |
| 9   | MANOVA / RM ANOVA               |             |             |
| 10   | Mixed models                    |             |             |
| 11   | Mediation                       |             |             |
